const ALLOWED_CURRENCIES = ["USD", "NGN", "GHS", "KES"];

const DEFAULT_CURRENCIES = ["USD", "NGN"];

const ALLOWED_CARD_BRANDS = ["VISA", "MASTERCARD"];

export { ALLOWED_CURRENCIES, DEFAULT_CURRENCIES, ALLOWED_CARD_BRANDS };